# WEBSERVICE CONFIGS
APP_PORT: '8080'

# EVENTHANDLER SERVICE CONFIGS
GRPC_SERVER_HOST: 'sq_event'
GRPC_SERVER_PORT: '8081'

# DATABASE CONFIGS
DATABASE_NAME: 'squadcast?parseTime=true'
DATABASE_HOST: 'sq_db'
DATABASE_PORT: ''
DATABASE_USER: 'root'
DATABASE_PASSWORD: 'easypeasy'
DATABASE_MIGRATIONS_DIR: 'internal/migrations'
DATABASE_DIALECT: 'mysql'

# RABBITMQ CONFIGS
RABBITMQ_ADDRESS: 'sq_rabbitmq:5672'
RABBITMQ_EXCHANGE: 'squadcast'

# APP RELATED CONFIGS
LOG_OUTPUT: 'console'