# WEB SERVER CONFIG
APP_PORT: '8080'

# GRPC SERVER CONFIG
GRPC_SERVER_HOST: 'localhost'
GRPC_APP_PORT: '8081'

# DATABASE CONFIG
DATABASE_MIGRATIONS_DIR: 'internal/migrations'
DATABASE_HOST: 'localhost'
DATABASE_PORT: '3307'
DATABASE_NAME: 'squadcast?parseTime=true'
DATABASE_USER: 'root'
DATABASE_PASSWORD: 'easypeasy'
DATABASE_DIALECT: 'mysql'

# APP CONFIGS
LOG_OUTPUT: 'console'