FROM golang:latest as builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . ./

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

FROM alpine:latest  

RUN apk update && apk add bash

WORKDIR /root/

EXPOSE 8080

COPY --from=builder /app/main .

COPY --from=builder /app/wait-for-it.sh /wait-for-it.sh

COPY --from=builder /app/application.prod.yaml /application.yaml

RUN chmod +x /wait-for-it.sh