FROM golang:latest as builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . ./

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main

FROM alpine:latest  

RUN apk --no-cache add ca-certificates

RUN apk add curl

WORKDIR /root/

CMD ["./main", "start:worker", "slack"]

COPY --from=builder /app/application.prod.yaml application.yaml

COPY --from=builder /app/main .